name: pet_age_estimation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8
  - numpy>=1.21.0
  - pillow>=9.0.0
  - tqdm>=4.65.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - matplotlib>=3.7.0
  - opencv>=4.7.0
  - pip>=23.0.0
  - pip:
    - segment-anything>=1.0
    - transformers>=4.30.0  # For ConvNeXTv2 and ViT models
    - timm>=0.9.0  # For advanced vision models
    - albumentations>=1.3.0  # For image augmentations 